### ISSUE TITLE
how to instance for multiple conversations?

### ISSUE THREAD

**Issue by dcsan** [codename-co/botml#41]
if we have a bot where `state` is managed internally, eg for variables or current conversation topic, how can we deal with an app that has multiple conversations?
for example passing a userId in when the bot is instantiated?

`const bot = new Botml('alice.bot')`

or, some way to set the state before the parser is run, which would mean a way to get at the resulting botState after a message parse and then set that state before a new message parse, keeping track of the user:state table ourselves.

**Comment by dcsan** [comment]
I found `bot.context.variables` but it doesn't seem to actually contain variables that are set by the script.

```
bot {
    "emitter": {
        "_events": {},
        "_eventsCount": 4
    },
    "context": {
        "emitter": {
            "_events": {},
            "_eventsCount": 4
        },
        "dialogues": {},
        "lists": {},
        "services": {},
        "variables": {
            "name": "variable",
            "emitter": {
                "_events": {},
                "_eventsCount": 4
            }
        },
        "workflows": {
            "name": "workflow",
            "emitter": {
                "_events": {},
                "_eventsCount": 4
            }
        },
        "patterns": {
            "name": "pattern",
            "emitter": {
                "_events": {},
                "_eventsCount": 4
            }
        },
        "switchModel": {
            "switchStatement": false,
            "startIteration": false,
            "currentCase": 0,
            "switchCases": [],
            "type": null
        },
        "activeCheckpoint": false,
        "saidSomething": false
    },
    "utils": {
        "context": {
            "emitter": {
                "_events": {},
                "_eventsCount": 4
            },
            "dialogues": {},
            "lists": {},
            "services": {},
            "variables": {
                "name": "variable",
                "emitter": {
                    "_events": {},
                    "_eventsCount": 4
                }
```

**Comment by dcsan** [comment]
OK as code it works this way, so I guess I could `set/get` the variables if I knew what they were called...

```
  log.info('age:', bot.context.variables.get('age'))
```

**Comment by codenametype** [comment]
Yes, you are right. You could `set` or `get` variables in `.bot/.js` script.
In `.bot` script:

```
~ case_1
> case 1
` context.variables.set('user_id', '1')
~ [show_user_id]

~ case_2
> case 2
` context.variables.set('user_id', '2')
~ [show_user_id]

~ show_user_id
< Your id is $user_id

```
[▶ Run](https://dev.bubl.es/#~%20case_1%0A%3E%20case%201%0A%60%20context.variables.set('user_id',%20'1')%0A~%20[show_user_id]%0A%0A~%20case_2%0A%3E%20case%202%0A%60%20context.variables.set('user_id',%20'2')%0A~%20[show_user_id]%0A%0A~%20show_user_id%0A%3C%20Your%20id%20is%20$user_id%0A)

In `.js` script:
```
bot.context.variables.set('user_id', '1');
bot.context.variables.get('user_id');
```

**Comment by arnaud** [comment]
Hi. I'm assuming the latest answer was useful, and this ticket closed.

Do not hesitate to reach again if not,
