### ISSUE TITLE
how does 'return' work from conditionals?

### ISSUE THREAD

**Issue by dcsan** [codename-co/botml#48]
sometimes when a conditional matches a response, the conversation will seem to return and continue.
but other times it does not. I can't quite figure out the logic.

given [this example](https://dev.bubl.es/#~%20start%0A%3C%20start%0A%20%20[intro]%0A~%20[colors]%0A~%20[ending]%0A%0A~%20colors%0A%3C%20Whats%20your%20favorite%20color?%0A---%0A%20%20%3E%20red%0A%20%20%3C%20roses%20are%20red%0A---%0A%20%20%3E%20blue%0A%20%20%3C%20sky%20is%20blue%0A---%0A%3E%20*{color}%0A%3C%20you%20like%20$color%0A%0A=%20intro%0A-%20Let's%20begin%0A%0A~%20ending%0A%3C%20Thanks%20and%20goodnight.%0A%0A%3E%20reset%0A~%20[start]%0A%0A)

on bubbles

```
~ start
< start
  [intro]
~ [colors]
~ [ending]

~ colors
< Whats your favorite color?
---
  > red
  < roses are red
---
  > blue
  < sky is blue
---
> *{color}
< you like $color

= intro
- Let's begin

~ ending
< Thanks and goodnight.

> reset
~ [start]

```

![image](https://user-images.githubusercontent.com/514002/62417621-01793080-b64c-11e9-87d7-ebd64698b4a4.png)

**Comment by dcsan** [comment]
if the match is inside one of the conditions it will not 'return'

```
---
  > red
  < roses are red
```

but if the reply is caught as the default/bottom entry of the logic block, then the code will return and continue, it seems.


![image](https://user-images.githubusercontent.com/514002/62417647-c1ff1400-b64c-11e9-8449-99a23a149dac.png)

**Comment by dcsan** [comment]
perhaps things would be better if there was a more explicit `@ return` or some type of keyword like that?

**Comment by arnaud** [comment]
You'll find the reasoning behind conditional, and some examples, in this post:
https://github.com/codename-co/botml/issues/42#issuecomment-518370648

The only way I can think of right now, for addressing your example, would go like this:

```
~ start
< start
  [intro]
~ [colors]
~ [ending]

~ colors
< Whats your favorite color?
> *{color}
< you like $color
\`\`\`
if ($color === 'blue') {
  context.say('sky is blue')
}
\`\`\`

= intro
- Let's begin

~ ending
< Thanks and goodnight.

> reset
~ [start]
```

[▶ Play this script](https://dev.bubl.es/#~%20start%0A%3C%20start%0A%20%20[intro]%0A~%20[colors]%0A~%20[ending]%0A%0A~%20colors%0A%3C%20Whats%20your%20favorite%20color?%0A%3E%20*{color}%0A%3C%20you%20like%20$color%0A%60%60%60%0Aif%20($color%20===%20'blue')%20{%0A%20%20context.say('sky%20is%20blue')%0A}%0A%60%60%60%0A%0A%0A=%20intro%0A-%20Let's%20begin%0A%0A~%20ending%0A%3C%20Thanks%20and%20goodnight.%0A%0A%3E%20reset%0A~%20[start]%0A%0A)

**Comment by codenametype** [comment]
Hi!
Sorry for the very late response.
According documentation [Conditional branching ](https://github.com/codename-co/botml#conditional-branches) last example.
[▶ Play this script](https://dev.bubl.es/#~%20start%0A%3C%20start%0A%20%20[intro]%0A~%20[colors]%0A~%20[ending]%0A%0A~%20colors%0A%3C%20Whats%20your%20favorite%20color?%0A%3E%20*{color}%0A---%0A%20%20%60%20/red/.test('$color')%0A%20%20%3C%20roses%20are%20red%0A%20%20~%20[end]%0A---%0A%20%20%60%20/blue/.test('$color')%0A%20%20%3C%20sky%20is%20blue%0A%20%20~%20[end]%0A---%0A%3C%20you%20like%20$color%0A~%20end%0A%0A=%20intro%0A-%20Let's%20begin%0A%0A~%20ending%0A%3C%20Thanks%20and%20goodnight.%0A%0A%3E%20reset%0A~%20[start]%0A%0A)

**Comment by arnaud** [comment]
Hi. I'm assuming the latest answer was useful, and this ticket closed.

Do not hesitate to reach again if not,
