### ISSUE TITLE
Does this support length wildcard???

### ISSUE THREAD

**Issue by I-am-Orion** [codename-co/botml#50]
Does this support length wildcard like superscript.js???
example:

```
+ hello *~2
- That is crazy!
```

● Matches ``` Hello John Doe ```
● Does not match ``` Hello John ```

``` + hello *(2-4)```

● Matches ``` Hello John Doe ``` and ``` Hello John Dorian Doe ```
● Does not match ``` Hello John ```

**Comment by arnaud** [comment]
It supports something way more extended and mature: regular expressions.

```
> /^Hello (?:\w+)/
< Cool bro.
```

More about using regex in the [documentation.](https://github.com/codename-co/botml#regular-expression).

I hope you'll find it useful to your use case?
