### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by dcsan** [codename-co/botml#7]
> Also, as per licensing, botml v1 is open source (MIT) so usable as-is in most situations, whereas botml v2 is copyrighted, with the software free to use in non-commercial projets; any commercial use of this version 2 needs a license, as per https://github.com/BotML/botml-js/blob/2.0-dev/LICENSE.txt

can you explain more your thoughts on this?

**Comment by arnaud** [comment]
Sorry for the verrryy late reply; the licensing information is all available to you in the [License file](https://raw.githubusercontent.com/codename-co/botml/master/LICENSE.txt).
